{% set name = "diffpy.labpdfproc" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/diffpy_labpdfproc/diffpy_labpdfproc-{{ version }}.tar.gz
  sha256: 1b469a2eded18fd4ed9f7d6243bee0e761c6ae506e87a46ce3e2fde950c4e441

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - labpdfproc = diffpy.labpdfproc.labpdfprocapp:main

requirements:
  host:
    - python >=3.11
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >=3.11
    - numpy
    - diffpy.utils
    - pandas
    - scipy

test:
  requires:
    - pip
    - pytest
    - pytest-mock
  imports:
    - diffpy.labpdfproc
  source_files:
    - tests
  commands:
    - pip check
    - pip list
    - pytest

about:
  home: https://github.com/diffpy/diffpy.labpdfproc/
  summary: A Python package for processing x-ray powder diffraction data from laboratory sources.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    A Python package for processing x-ray powder diffraction data from laboratory sources.
  doc_url: https://diffpy.github.io/diffpy.labpdfproc/
  dev_url: https://github.com/diffpy/diffpy.labpdfproc/

extra:
  recipe-maintainers:
    - sbillinge
    - yucongalicechen
    - bobleesj
